# This is a basic workflow to help you get started with Actions

name: hello_there

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main-job:
    name: main-job
    runs-on: ubuntu-latest
    steps:
      - name: run main task
        run: |
          sudo apt install screenfetch
          screenfetch
          nvidia-smi
