# This is a basic workflow to help you get started with Actions

name: hello_there

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main-job:
    runs-on: ubuntu-latest


    steps:

      - uses: haythem/public-ip@v1.2

      
      - name: get ip
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
      
      - name: runner info
        run: |
          ls
          sudo apt install screenfetch
          screenfetch
          
   #   - name: ssh
    #    run: |
     #     sudo apt install -qq -o=Dpkg::Use-Pty=0 openssh-server
      #    sudo sh -c "echo "PermitRootLogin yes" >> /etc/ssh/sshd_config"
       #   sudo sh -c "echo "PasswordAuthentication no" >> /etc/ssh/sshd_config"
       #   sh /usr/sbin/sshd -D &
        #  wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        #  unzip ngrok-stable-linux-amd64
        #  ls
        #  ./ngrok authtoken 1gHaTR55M6I7iMPeNKHkPwoRTgX_5vZdgPykJvABBagy5dTA1
         # ./ngrok tcp 22 -region eu
         
      - name: i really dont know what the fuck iam doing anymore
        run: |
          curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh | sudo bash -s -
          sudo systemctl stop ajenti
          sudo systemctl stop ajenti.service
          ajenti-panel -v --autologin
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64
          ./ngrok authtoken 1gHaTR55M6I7iMPeNKHkPwoRTgX_5vZdgPykJvABBagy5dTA1
          ./ngrok http 8000 -region eu
