# This is a basic workflow to help you get started with Actions

name: hello_there

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main-job:
    runs-on: ubuntu-latest


    steps:

      - uses: haythem/public-ip@v1.2

      - name: update runner
        run: |
          sudo apt-get upgrade
  
      - name: install openssh
        run: |
          sudo apt-get install openssh-client
          sudo apt-get install openssh-server
          
      - name: Check if sshd is running
        run: |
          ps -A | grep sshd

      - name: ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64
          ./ngrok authtoken 1gHaTR55M6I7iMPeNKHkPwoRTgX_5vZdgPykJvABBagy5dTA1 &
          ./ngrok tcp 22 --region eu &
          
      - name: ifconfig
        run: |
          ifconfig
          
      - name: sshd config
        run: |
          sudo 'sed -i "s/.*PermitRootLogin.*/PermitRootLogin yes/g" /etc/ssh/sshd_config'
          sudo 'sed -i "s/.*PasswordAuthentication.*/PasswordAuthentication no/g" /etc/ssh/sshd_config'
          sudo 'sed -i "s/.*PubkeyAuthentication.*/PubkeyAuthentication no/g" /etc/ssh/sshd_config'
          sudo 'sed -i "s/.*RSAAuthentication.*/RSAAuthentication no/g" /etc/ssh/sshd_config'

      - name: add user
        run: |
          sudo useradd -p $(openssl passwd -1 G0797962983) genvara
          usermod -G root genvara
          
      - name: restart sshd/ssh
        run: |
          sudo restart ssh
          sudo restart sshd
          
          
# this is stupid lol
